Adjust upgrade journey Raft pipeline to v1.30

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -130,6 +130,20 @@ jobs:
           first: ${{ needs.real-version-in-tag.outputs.real_version }}
           second: "1.30.0"
           operator: ">="
+  older-than-1_30:
+    name: "Check if the version is older than 1.30"
+    needs: real-version-in-tag
+    runs-on: ubuntu-latest
+    outputs:
+      check: ${{ steps.semver_compare.outputs.result }}
+    steps:
+      - name: Semver Compare
+        id: semver_compare
+        uses: fabriziocacicia/semver-compare-action@v0.1.0
+        with:
+          first: ${{ needs.real-version-in-tag.outputs.real_version }}
+          second: "1.30.0"
+          operator: "<"
   filter-memory-leak:
     name: Filter (cache) memory leak when querying while importing
     if: ${{ github.event.inputs.test_to_run == 'filter-memory-leak' || github.event.inputs.test_to_run == '' }}
@@ -1285,8 +1299,8 @@ jobs:
       - name: Run chaos test
         run: ./upgrade_single_node_journey.sh
   upgrade-journey-raft:
-    needs: [newer-or-equal-than-1_25]
-    if: ${{ (needs.newer-or-equal-than-1_25.outputs.check == 'true') && ( github.event.inputs.test_to_run == 'upgrade-journey-raft' || github.event.inputs.test_to_run == '')}}
+    needs: [newer-or-equal-than-1_25, older-than-1_30]
+    if: ${{ (needs.newer-or-equal-than-1_25.outputs.check == 'true') && ((needs.older-than-1_30.outputs.check == 'true')) && ( github.event.inputs.test_to_run == 'upgrade-journey-raft' || github.event.inputs.test_to_run == '')}}
     name: Upgrade to Raft journey e2e test
     runs-on: ubuntu-latest
     timeout-minutes: 60
@@ -1386,6 +1400,132 @@ jobs:
           modules: 'text2vec-contextionary'
           values-inline: '--set env.PERSISTENCE_LSM_ACCESS_STRATEGY=${{env.PERSISTENCE_LSM_ACCESS_STRATEGY}}'
           delete-sts: 'true'
+      - name: Weaviate preview image - check additional and old data
+        run: |
+          cd apps/upgrade-journey-raft
+          python3 additional_checks.py
+      - name: Archive logs
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: upgrade-journey-raft-${{ inputs.lsm_access_strategy }}-logs
+          path: apps/upgrade-journey-raft/logs/
+  upgrade-journey-raft-1_30:
+    needs: [newer-or-equal-than-1_30]
+    if: ${{ (needs.newer-or-equal-than-1_30.outputs.check == 'true') && ( github.event.inputs.test_to_run == 'upgrade-journey-raft-1_30' || github.event.inputs.test_to_run == '')}}
+    name: Upgrade to Raft journey e2e test v1.30
+    runs-on: ubuntu-latest
+    timeout-minutes: 60
+    env:
+      WEAVIATE_NON_RAFT_VERSION: 1.24.15
+      WEAVIATE_RAFT_VERSION_1: 1.25.0
+      WEAVIATE_RAFT_VERSION_1_29: 1.29.0
+      PERSISTENCE_LSM_ACCESS_STRATEGY: ${{inputs.lsm_access_strategy}}
+    steps:
+      - uses: actions/checkout@v3
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{secrets.DOCKER_USERNAME}}
+          password: ${{secrets.DOCKER_PASSWORD}}
+      - name: Install python dependencies
+        run: |
+          cd apps/upgrade-journey-raft
+          pip3 install -r requirements.txt
+      - name: Weaviate v1.24.x - setup K8s 3-node cluster
+        uses: weaviate/weaviate-local-k8s@v2
+        with:
+          operation: 'setup'
+          workers: '1'
+          replicas: '3'
+          weaviate-version: ${{env.WEAVIATE_NON_RAFT_VERSION}}
+          modules: 'text2vec-contextionary'
+          values-inline: '--set podManagementPolicy=OrderedReady --set env.PERSISTENCE_LSM_ACCESS_STRATEGY=${{env.PERSISTENCE_LSM_ACCESS_STRATEGY}}'
+      - name: Weaviate v1.24.x - import data
+        run: |
+          cd apps/upgrade-journey-raft
+          python3 run.py
+      - name: Weaviate v1.24.x - check data after import
+        run: |
+          cd apps/upgrade-journey-raft
+          python3 checks.py
+      - name: Weaviate v1.25.0 - upgrade K8s cluster from non-raft to Raft version
+        uses: weaviate/weaviate-local-k8s@v2
+        with:
+          operation: 'upgrade'
+          workers: '1'
+          replicas: '3'
+          weaviate-version: ${{env.WEAVIATE_RAFT_VERSION_1}}
+          modules: 'text2vec-contextionary'
+          values-inline: '--set env.PERSISTENCE_LSM_ACCESS_STRATEGY=${{env.PERSISTENCE_LSM_ACCESS_STRATEGY}}'
+          delete-sts: 'true'
+      - name: Weaviate v1.25.0 - check data after upgrade to Raft version
+        run: |
+          cd apps/upgrade-journey-raft
+          python3 checks.py
+      - name: Weaviate v1.29.0 image - upgrade K8s from Raft to another Raft version (rolling update)
+        uses: weaviate/weaviate-local-k8s@v2
+        with:
+          operation: 'upgrade'
+          workers: '1'
+          replicas: '3'
+          weaviate-version: ${{env.WEAVIATE_RAFT_VERSION_1_29}}
+          modules: 'text2vec-contextionary'
+          values-inline: '--set env.PERSISTENCE_LSM_ACCESS_STRATEGY=${{env.PERSISTENCE_LSM_ACCESS_STRATEGY}}'
+      - name: Weaviate v1.29.0 image - check old data
+        run: |
+          cd apps/upgrade-journey-raft
+          python3 checks.py
+      - name: Weaviate v1.29.0 image - add additional data and check all (old and new) data
+        run: |
+          cd apps/upgrade-journey-raft
+          python3 additional_run.py
+          python3 additional_checks.py
+      - name: Weaviate v1.29.0 image - sync with schema V1
+        run: |
+          if [ "$(curl -X POST -s -o /dev/null -w "%{http_code}" localhost:8080/v1/cluster/schema-v1)" != "200" ]; then
+            echo "Synchronization of schema V1 failed"
+            exit 1
+          else
+            echo "Schema V1 succesfully synchronized"
+          fi
+      - name: Weaviate v1.24.x - downgrade from Raft to none-raft version
+        uses: weaviate/weaviate-local-k8s@v2
+        with:
+          operation: 'upgrade'
+          workers: '1'
+          replicas: '3'
+          weaviate-version: ${{env.WEAVIATE_NON_RAFT_VERSION}}
+          modules: 'text2vec-contextionary'
+          values-inline: '--set podManagementPolicy=OrderedReady  --set env.PERSISTENCE_LSM_ACCESS_STRATEGY=${{env.PERSISTENCE_LSM_ACCESS_STRATEGY}}'
+          delete-sts: 'true'
+      - name: Weaviate v1.24.x - check additional and old data
+        run: |
+          cd apps/upgrade-journey-raft
+          python3 additional_checks.py
+      - name: Weaviate v1.29.0 image - upgrade K8s from none-raft to Raft version
+        uses: weaviate/weaviate-local-k8s@v2
+        with:
+          operation: 'upgrade'
+          workers: '1'
+          replicas: '3'
+          weaviate-version: ${{env.WEAVIATE_RAFT_VERSION_1_29}}
+          modules: 'text2vec-contextionary'
+          values-inline: '--set env.PERSISTENCE_LSM_ACCESS_STRATEGY=${{env.PERSISTENCE_LSM_ACCESS_STRATEGY}}'
+          delete-sts: 'true'
+      - name: Weaviate preview image - check additional and old data
+        run: |
+          cd apps/upgrade-journey-raft
+          python3 additional_checks.py
+      - name: Weaviate preview image - upgrade from v1.29.0 to preview image (rolling update)
+        uses: weaviate/weaviate-local-k8s@v2
+        with:
+          operation: 'upgrade'
+          workers: '1'
+          replicas: '3'
+          weaviate-version: ${{env.WEAVIATE_VERSION}}
+          modules: 'text2vec-contextionary'
+          values-inline: '--set env.PERSISTENCE_LSM_ACCESS_STRATEGY=${{env.PERSISTENCE_LSM_ACCESS_STRATEGY}}'
       - name: Weaviate preview image - check additional and old data
         run: |
           cd apps/upgrade-journey-raft
