Add rolling/single-pod restarts QPS/latency pipeline.
The purpose of theses pipeline is ensuring that Weaviate
isn't so sensitive to rolling restarts from the point
of view of data ingestion as well as querying.
The pipeline creates one or several collections,
ingest data in the background, then starts a QPS
benchmark which stores latency and QPS and while both
ingestion and QPS is taking place it can either perform:
- a rollout restart
- a single node restart (starting by a non leader and following
by a leader).
The pipeline checks that the QPS and latencies obtained
are within a threshold, also stores relevant metrics and dashboards
for post-analsys.

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -2685,3 +2685,150 @@ jobs:
           path: |
             apps/alter_schema_operations/logs/
             /tmp/weaviate*
+
+  rolling-restart-highly-available-qps-benchmark:
+    needs: [newer-or-equal-than-1_31, newer-or-equal-than-1_36]
+    if: ${{ (needs.newer-or-equal-than-1_31.outputs.check == 'true') && ( github.event.inputs.test_to_run == 'rolling-restart-highly-available-qps-benchmark' || github.event.inputs.test_to_run == '')}}
+    name: Measuring QPS during rolling restart
+    runs-on: ubicloud-standard-8
+    timeout-minutes: 60
+    env:
+      OBJECTS_PER_CLASS: 15000
+      BATCH_SIZE: 1000
+      # disable WAL reuse, otherwise pipeline will fail because of an unknown commit type (CommitTypeRoaringSetList) that was added in 1.25
+      VALUES_OVERRIDE: |
+        env:
+          ASYNC_INDEXING: true
+          ASYNC_REPLICATION_FREQUENCY: "10s"
+          PERSISTENCE_LSM_ACCESS_STRATEGY: ${{inputs.lsm_access_strategy}}
+          PERSISTENCE_MAX_REUSE_WAL_SIZE: 0 
+          RAFT_TIMEOUTS_MULTIPLIER: 5
+          MEMBERLIST_FAST_FAILURE_DETECTION: true
+          ${{ needs.newer-or-equal-than-1_36.outputs.check != 'true' && 'DISABLE_LAZY_LOAD_SHARDS: true' || '' }}
+          ${{ needs.newer-or-equal-than-1_36.outputs.check != 'true' && 'HNSW_STARTUP_WAIT_FOR_VECTOR_CACHE: true' || '' }}
+      # Only include HNSW_STARTUP_WAIT_FOR_VECTOR_CACHE and DISABLE_LAZY_LOAD_SHARDS if version is older than 1.36.0
+    steps:
+      # - name: Collect Workflow Telemetry
+      #   uses: catchpoint/workflow-telemetry-action@v2
+      - uses: actions/checkout@v5
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{secrets.DOCKER_USERNAME}}
+          password: ${{secrets.DOCKER_PASSWORD}}
+      - name: Install python dependencies
+        run: |
+          cd apps/restart-highly-available-qps-benchmark
+          pip3 install -r requirements.txt
+      - name: Weaviate - setup K8s 3-node cluster
+        uses: weaviate/weaviate-local-k8s@v2
+        with:
+          operation: 'setup'
+          workers: '2'
+          replicas: '4'
+          weaviate-version: ${{env.WEAVIATE_VERSION}}
+          modules: 'text2vec-transformers-model2vec'
+          values-override: ${{env.VALUES_OVERRIDE}}
+      - name: Start stern to capture logs
+        uses: weaviate/github-common-actions/.github/actions/capture-logs@main
+        with:
+          action: start
+      - name: Weaviate - create collections and ingest data in the background
+        run: |
+          cd apps/restart-highly-available-qps-benchmark
+          python3 ingest_and_benchmark_qps.py rolling-restart
+      - name: Stop stern
+        if: always()
+        uses: weaviate/github-common-actions/.github/actions/capture-logs@main
+        with:
+          action: stop
+      - name: Archive logs
+        if: always()
+        uses: actions/upload-artifact@v5
+        with:
+          name: rolling-restart-highly-available-qps-benchmark-${{ inputs.lsm_access_strategy }}-logs
+          path: |
+            apps/restart-highly-available-qps-benchmark/benchmark_results*
+            /tmp/weaviate*
+      - name: Check for panics in logs
+        if: always()
+        run: |
+          if grep -iE "panic:|runtime error:|goroutine.*\[running\]" /tmp/weaviate_pods.log; then
+            echo "::error::Found panic in weaviate logs"
+            echo "Panic context:"
+            grep -A 20 -iE "panic:|runtime error:|goroutine.*\[running\]" /tmp/weaviate_pods.log
+            exit 1
+          fi
+  single-pod-restart-highly-available-qps-benchmark:
+    needs: [newer-or-equal-than-1_31, newer-or-equal-than-1_36]
+    if: ${{ (needs.newer-or-equal-than-1_31.outputs.check == 'true') && ( github.event.inputs.test_to_run == 'single-pod-restart-highly-available-qps-benchmark' || github.event.inputs.test_to_run == '')}}
+    name: Measuring QPS during single-pod restart. Starts with a non-RAFT leader pod restart followed by the RAFT leader pod restart.
+    runs-on: ubicloud-standard-8
+    timeout-minutes: 60
+    env:
+      OBJECTS_PER_CLASS: 15000
+      BATCH_SIZE: 1000
+      # disable WAL reuse, otherwise pipeline will fail because of an unknown commit type (CommitTypeRoaringSetList) that was added in 1.25
+      VALUES_OVERRIDE: |
+        env:
+          ASYNC_INDEXING: true
+          ASYNC_REPLICATION_FREQUENCY: "10s"
+          PERSISTENCE_LSM_ACCESS_STRATEGY: ${{inputs.lsm_access_strategy}}
+          PERSISTENCE_MAX_REUSE_WAL_SIZE: 0 
+          RAFT_TIMEOUTS_MULTIPLIER: 5
+          MEMBERLIST_FAST_FAILURE_DETECTION: true
+          ${{ needs.newer-or-equal-than-1_36.outputs.check != 'true' && 'DISABLE_LAZY_LOAD_SHARDS: true' || '' }}
+          ${{ needs.newer-or-equal-than-1_36.outputs.check != 'true' && 'HNSW_STARTUP_WAIT_FOR_VECTOR_CACHE: true' || '' }}
+      # Only include HNSW_STARTUP_WAIT_FOR_VECTOR_CACHE and DISABLE_LAZY_LOAD_SHARDS if version is older than 1.36.0
+    steps:
+      # - name: Collect Workflow Telemetry
+      #   uses: catchpoint/workflow-telemetry-action@v2
+      - uses: actions/checkout@v5
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ${{secrets.DOCKER_USERNAME}}
+          password: ${{secrets.DOCKER_PASSWORD}}
+      - name: Install python dependencies
+        run: |
+          cd apps/restart-highly-available-qps-benchmark
+          pip3 install -r requirements.txt
+      - name: Weaviate - setup K8s 3-node cluster
+        uses: weaviate/weaviate-local-k8s@v2
+        with:
+          operation: 'setup'
+          workers: '2'
+          replicas: '4'
+          weaviate-version: ${{env.WEAVIATE_VERSION}}
+          modules: 'text2vec-transformers-model2vec'
+          values-override: ${{env.VALUES_OVERRIDE}}
+      - name: Start stern to capture logs
+        uses: weaviate/github-common-actions/.github/actions/capture-logs@main
+        with:
+          action: start
+      - name: Weaviate - create collections and ingest data in the background
+        run: |
+          cd apps/restart-highly-available-qps-benchmark
+          python3 ingest_and_benchmark_qps.py single-pod-restart
+      - name: Stop stern
+        if: always()
+        uses: weaviate/github-common-actions/.github/actions/capture-logs@main
+        with:
+          action: stop
+      - name: Archive logs
+        if: always()
+        uses: actions/upload-artifact@v5
+        with:
+          name: single-pod-restart-highly-available-${{ inputs.lsm_access_strategy }}-logs
+          path: |
+            apps/restart-highly-available-qps-benchmark/benchmark_results*
+            /tmp/weaviate*
+      - name: Check for panics in logs
+        if: always()
+        run: |
+          if grep -iE "panic:|runtime error:|goroutine.*\[running\]" /tmp/weaviate_pods.log; then
+            echo "::error::Found panic in weaviate logs"
+            echo "Panic context:"
+            grep -A 20 -iE "panic:|runtime error:|goroutine.*\[running\]" /tmp/weaviate_pods.log
+            exit 1
+          fi
